### ISSUE TITLE
will turtle format for RDF be added into serializer again?

### ISSUE THREAD

**Issue by zealot-shin** [ldbc/ldbc_snb_docs#163]
i noticed that turtle serializer  had been removed in April.
Since rdf fromat is neccessary in our cases, i wonder if turtle serializer  will be added in again?

**Comment by szarnyasg** [comment]
Hello @zealot-shin,

it has indeed been removed and putting it back is currently has not been a priority -- primarily because not many users have requested it so far. However, if there is interest, we can definitely assign a higher priority to it.
This will take a few months. 
For the time being, I have TTL data sets pre-generated up to SF30, so I can share you the links if that helps.

Can you elaborate a bit more on your requirements?

1. What is your uses case, e.g. what system(s) do you intend to benchmark? (no problem if you cannot)
2. Do you plan to use *deletion operations* (and not just inserts) in your workload?
3. What scale factors do you plan to use?

**Comment by zealot-shin** [comment]
In fact, I'm trying to compare some graph database's performance like nebula and dgraph and so on.
Dgraph is rdf based, thus the question been asked.

sharing me pre-generated TTL data will do me a big favour(hope that net traffic speed may not be a problem).
In my case, SF 0.1 ~ 1 is enough.

as to the requirements:
1,graph database comparing
2,deletion op should be considered
3, SF 0.1 ~ 1

**Comment by szarnyasg** [comment]
Hi, thanks for the answers.

The currently available TTLs do not have deletes -- for that, we'll need to reintroduce the turtle serializer in the current version of the generator.

I'm sharing the TTLs in a separate comment that'll be deleted in a few days (so save the URL).

**Comment by szarnyasg** [comment]
Here are the pre-generated TTLs:
https://www.dropbox.com/sh/jnfgfgkbmdhrp93/AAAZTHV-IA_3t-vX4IysSN25a?dl=0
